import Sidebar from "@/components/Sidebar";
import "./globals.css";
import News from "@/components/News";


export const metadata = {
  title: "X",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-between max-w-6xl mx-auto">

          <div>
            <Sidebar />
          </div>


          <div>
            {children}
          </div>

          <div>
            <News />
          </div>
          
        </div>
        {/* <div className="bg-red-500 md:hidden">
          {children}
        </div> */}
      </body>
    </html>
  );
}
